### ISSUE TITLE
[BUG] Issue between secureblue kargs and Nvidia driver

### ISSUE THREAD

**Issue by sinniti1** [secureblue/secureblue#255] opened 2024-04-07 00:43 UTC
Nvidia driver is not working properly when secureblue's kargs hardening is set.

For example, when using distrobox OBS I cannot use NVENC as video encoder, it will result:
```
Failed to open NVENC codec: Unknown error occured

Try installing the latest NVIDIA driver.
```
Or in flatpak OBS, I even cannot found NVENC as a option to choose as video encoder, it will just show x264.

Another example, `ujust configure-nvidia` to test CUDA support, it will also not work and result:

> `The Nvidia kernel module is not loaded. You may be using secure boot without the needed signing key, lacking the needed kargs, or may not be on a Nvidia image.`

To note that, I disabled secure boot, Nvidia kargs are set, and on Nvidia image.

To reproduce:
1. Rebase image
2. Set secureblue's hardening kargs and reboot (`ujust set-kargs-hardening && systemctl reboot`)
3. Test CUDA support (`ujust configure-nvidia`
 and choose Test CUDA support)
4. Install OBS and choose NVENC as video encoder (`ujust install-obs-studio-portable` to install on distrobox or install flatpak in software store)

Expected result:
Able to test CUDA/use NVENC as encoder.

Actual result:
Not working.

Current image:
secureblue/silverblue-asus-nvidia-userns-hardened

Tested image:
secureblue/silverblue-nvidia-userns-hardened
ublue-os/silverblue-asus-nvidia
ublue-os/silverblue-nvidia

**Comment by RoyalOughtness** [comment] 2024-04-07 00:50
can you please narrow down which karg is causing the issue by starting with none of them and then applying them one at a time until it breaks?

**Comment by sinniti1** [comment] 2024-04-07 01:09
Ok I will try

**Comment by sinniti1** [comment] 2024-04-07 03:36
So disable these kargs, the driver will works:

`lockdown=confidentiality`
`module.sig_enforce=1`

After reboot I faced a problem that extra monitor will not work, you may see the bootsplash when you boot up or shut down, and the LUKS password screen, but besides of these the second monitor will not work.

BUT after several reboots, kargs edits, rollbacks (yeah I redo it again and again), the monitor works now.

**Comment by RoyalOughtness** [comment] 2024-04-07 05:28
@sinniti1 does it work with each of those set separately, and only fail with them used together?

Regardless please report this to the asus kernel maintainer here: https://gitlab.com/asus-linux/fedora-kernel/-/issues

**Comment by sinniti1** [comment] 2024-04-07 09:03
Both of them have to disable, if one of them enabled then the module won't work.

**Comment by RoyalOughtness** [comment] 2024-04-13 18:59
reopening this as it's not specific to asus, and another user is able to reproduce it

**Comment by alexispurslane** [comment] 2024-04-15 12:09
This may actually be the source of a problem I'm also having, so let me attempt to see if I can reproduce this.

Edit: nope, all my distroboxes just refuse to do cuda for a different reason.

**Comment by RoyalOughtness** [comment] 2024-04-23 00:54
Can someone test whether this reproduces on Fedora Workstation? In particular with lockdown=confidentiality + nvidia drivers?

I haven't been able to test this properly as I'm unable to reproduce it on my hardware.

If someone can confirm that this reproduces on Workstation, I can file a bug report upstream to RPMFusion.

**Comment by TheHooly** [comment] 2024-04-23 15:33
The Nvidia driver (and third-party drivers in general) needs to be validly signed in order to work with lockdown mode (is automatically engaged when Secure Boot is enabled and implies `module.sig_enforce`) and/or `module.sig_enforce` by itself.

For Silverblue and its derivatives, the usual akmod signing mechanism doesn't work because `/etc` is not accessible by the update process from `rpm-ostree`, see: https://github.com/fedora-silverblue/issue-tracker/issues/499

The following repo provides a workaround for this problem by including the `MOK` in an RPM package and layering it with `rpm-ostree`: 
https://github.com/CheariX/silverblue-akmods-keys

Alternatively, one can use `just enroll-secure-boot-key` to enroll uBlue's certificate as a MOK which will unblock all kernel modules signed by uBlue: https://github.com/ublue-os/akmods
The downside being that this approach doesn't work for kernel modules that are not included.

**Comment by RoyalOughtness** [comment] 2024-04-23 16:09
@TheHooly oh. perhaps that's why I'm unable to reproduce this, since I ran that command already. For some reason I was assuming that secureboot was already being used here.

@sinniti1 if you run `ujust enroll-secure-boot-key`, does that fix the issue?

**Comment by sinniti1** [comment] 2024-04-26 01:15
@qoijjj No, I disabled the secure boot as the Asus image cannot boot when enabling. I saw someone reported it as an issue on ublue/hwe. 

But I still tried, on the latest f40. I first `ujust set-karg-hardening` and `enroll-secure-boot-key` then reboot. The Nvidia card still not working though.

**Comment by TheHooly** [comment] 2024-04-27 06:19
> @qoijjj No, I disabled the secure boot as the Asus image cannot boot when enabling. I saw someone reported it as an issue on ublue/hwe. 
> 
> But I still tried, on the latest f40. I first `ujust set-karg-hardening` and `enroll-secure-boot-key` then reboot. The Nvidia card still not working though.

You cannot enroll the key when Secure Boot is disabled, and without any keys whitelisted the kernel will reject all dynamic kernel modules.

This is working as intended, you need to either setup Secure Boot correctly, or disable kernel lockdown.

**Comment by RoyalOughtness** [comment] 2024-04-27 06:46
Closing as working as intended

**Closed as not planned by RoyalOughtness** 2024-04-27 06:46 UTC

**Comment by sinniti1** [comment] 2024-05-04 03:04
@TheHooly Thanks! Yeah you're right, just the Asus image cannot setup secure boot properly due to this [issue](https://github.com/ublue-os/hwe/issues/221). But on the main image it will work.
