### ISSUE TITLE
Custom Greeting dialogs for GNOME and KDE

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#64] opened 2023-11-27 21:35 UTC
Both projects offer greeting dialogs that just work by default. If they don't work, you can file bugs upstream.

Both dialogs allowing the creation of custom pages, which can be helpful for explaining the complete concept of this distro.
Images, Screenshots, GIFs can be integrated, as well as links (at least for KDE).

**Comment by RoyalOughtness** [comment] 2023-11-27 21:44
We can use yafti for this

**Comment by boredsquirrel** [comment] 2023-11-29 23:36
If upstream Silverblue/Kinoite get customized greeting dialogs for regular problems like installing apps, we should maybe overthink this. Until then, agree

**Comment by RoyalOughtness** [comment] 2023-11-29 23:43
duplicate of https://github.com/secureblue/secureblue/issues/65

**Closed as not planned by RoyalOughtness** 2023-11-29 23:43 UTC
