### ISSUE TITLE
Rebasing from userNS image to Main and cannot launch any programs

### ISSUE THREAD

**Issue by moonlitOrca** [secureblue/secureblue#728] opened 2024-12-24 03:16 UTC
**Describe the bug**

**To Reproduce**
1. Running kinoite-main-userns image
2. Rebase to kinoite-main-hardened without userns
3. Try to launch any flatpak (for example flatseal)
4. Error returned that bwrap failed to create new namespace: permission denied. Ldconfig failed, exit status 256

**Expected behavior**
new image will function correctly without userns needs for flatpak

**Actual behavior**
I'm sure that I'm doing something wrong, so hopefully it's a simple thing that someone can lead me in the right direction. I don't use discord or else I would ask there.  I rebased to the kinoite main image because I saw that the userNS image I was on is being phased out.  I did read the recommendations and figured I'd have to tweak to make Steam work, but it seems like there's some configuration going on with bubble wrap perhaps that's preventing most of the programs from launching at all, and I assume it's because they are flatpaks (including the preinstalled chromium?)

**Your current image**
 41.20241223.0 (I would copy and paste all the text, but I can't open a web browser in the installation right now so I'm just typing in the relevant info here)

*¹*For all images**
-It seems like this last bullet point is asking about reproducing it on a UBlue image, but I don't have any other installs?

**Comment by RoyalOughtness** [comment] 2024-12-24 05:10
How old was your previous deployment?

This is an old issue but only if the image you're rebasing from has rpm-ostree 2024.8 or lower

Generating any kind of new deployment and rebooting will fix jt

**Comment by moonlitOrca** [comment] 2024-12-24 06:07
Hmmmmm ... I was updating it  almost every day using rpm-ostree update, so I don't think that my deployment was very old. Unless there was some error that I wasn't noticing that kept it from updating.  I'm glad to hear that there's a fix that shouldn't be too complicated, but what does it mean to generate a new deployment?  I would have imagined it was rebasing, but I just did that of course. 

How would I generate a new deployment?  I apologize for my ignorance on that, the atomic structure is a bit new to me.

**Comment by moonlitOrca** [comment] 2024-12-26 01:10
OK, So I have worked on this a bit over the last two days, and I think I managed to make another deplyoment by removing a layered package and updating.  Now my flatpaks are working again, but Chromium oddly is NOT.  When I run the Chromium binary from the shell `./usr/bin/chromium-browser`, I get the following error:

>  Checking version
>   Installed version: 1735095457
>   Package version: 1735095457
> No need to update, versions match
> [4290:4290:1225/200524.133288:ERROR:process_singleton_posix.cc(358)] The profile appears to be in use by another Chromium process (3094) on another computer (fedora). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.
> [4290:4290:1225/200524.133344:ERROR:message_box_dialog.cc(190)] Unable to show message box: Chromium - The profile appears to be in use by another Chromium process (3094) on another computer (fedora). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.
> 

It's worth mentioning that I got a similar warning about another profile active when I opened LiibreOffice Writer.  I have no idea what that means.  Is this related?

**Comment by moonlitOrca** [comment] 2024-12-26 02:14
After some research into this, it appears that probably this was caused by rebasing to the new image that uses a different hostname?  If this is the case, then I assume I can simply [remove the singletonlock file as discussed here](https://askubuntu.com/questions/297397/google-chrome-profile-in-use-browser-does-not-start-anymore), as that does seem to resolve the errors.

I want to make sure whatever I am doing is the correct process, so please correct me if I am wrong about anything so far, but I think that makes sense to me.  Are there any other things/issues I should check anent the rebase to the new Main-hardened image that might crop up later?  

Also, thanks for what you are doing!  I think this project has potential to be very valuable project for the open source world, and I'm happy to support it!

**Comment by RoyalOughtness** [comment] 2024-12-26 21:21
> Hmmmmm ... I was updating it almost every day using rpm-ostree update, so I don't think that my deployment was very old. Unless there was some error that I wasn't noticing that kept it from updating. I'm glad to hear that there's a fix that shouldn't be too complicated, but what does it mean to generate a new deployment? I would have imagined it was rebasing, but I just did that of course.
> 
> How would I generate a new deployment? I apologize for my ignorance on that, the atomic structure is a bit new to me.

np, essentially all rpm-ostree operations generate a new deployment

`rpm-ostree install`? new deployment
`rpm-ostree upgrade`? new deployment
`rpm-ostree rebase`? new deployment

etc

new deployment meaning that a new root filesystem will be booted into on next boot.

> updating it almost every day using rpm-ostree update

were you rebooting after updating? updates don't take effect unless you reboot.

> Also, thanks for what you are doing! I think this project has potential to be very valuable project for the open source world, and I'm happy to support it!

appreciate it

closing this as it appears the issue is solved. let me know if that's not the case

**Closed as not planned by RoyalOughtness** 2024-12-26 21:21 UTC
