### ISSUE TITLE
[BUG] Unable to Automatically Find Network Printer And Driver And Scanner When CUPS is Enabled

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#225] opened 2024-03-01 14:50 UTC
**Describe the bug**

The gnome setting fail to find printer and the driver for the printer even after running `just enable-cups`. The printer can be manually connected via IP addresses, but the driver needs to be selected from a list of drivers, instead of detected automatically. After the printer is installed, the scanner cannot be used by the gnome `document scanner` app.

The printer is one of `Canon MX490` series printers (includes builtin scanner), and this problem does not appear on fresh-install of fedora silverblue, and it does not appear on my other ubuntu laptop.

I am not sure if this is reproducible on other machine. I am planning to do more investigation in the coming days, but I am quite busy recently. It would be great to see if others can reproduce the issue.

**Additional Info**: printer can also be installed via `lpadmin -p Printer -E -v ipp://<IP Address>/ipp/print -m everywhere`, which detects the driver and prints normally, but the Documents Scanner still cannot find the scanner.

**To Reproduce**
1. `just enable-cups`
2. Go to gnome setting, and search for network printer, find nothing
3. Manually add printer, will let you select from a list of driver instead of detecting it.
4. After selecting the correct driver, the printer is connected.
5. Document Scanner cannot find the printer

**Expected behavior**

**Actual behavior**
printer should automatically detect, driver automatically installed, and Document Scanner should find the scanner

**Your current image**
```
$ rpm-ostree status -vb
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● ostree-unverified-registry:ghcr.io/secureblue/silverblue-nvidia-hardened:latest (index: 0)
                   Digest: sha256:c63cb0d28bcd3a2e73d0b7ad98f434ab9be5a3b4b9296508eb50db1ea5b448a5
                  Version: 39.20240229.0 (2024-03-01T05:07:23Z)
               BaseCommit: c5efd62d4c22c9e80440e655a0e35c37ebd9752e754ccafff0025c39337341d3
                   Commit: 6b62d89c1d3f72866a3359d5fb38face4316b52b8a26884b27ebfa2a6b6a34bf
                   Staged: no
                StateRoot: fedora
          LayeredPackages: langpacks-en
```

**For all images**
I cannot reproduce this on a fresh silverblue image, but haven't tried ublue image. I will try an ublue image soon.

**Comment by RoyalOughtness** [comment] 2024-03-01 16:52
please provide results from the ublue silverblue-nvidia image

also, please provide the output of `systemctl status cups`

also, why are you still on an unverified image? :smile:

**Comment by czhang03** [comment] 2024-03-01 16:57
> also, why are you still on an unverified image? 😄

LOL, I was planning to reinstall my OS, and figure testing some bugs I encountered on a fresh install, so I am on the unverified image. I am planning to reinstall and rebase to a verified image when I am done testing.

**Comment by RoyalOughtness** [comment] 2024-03-01 16:59
Ok, just FYI rebasing from the unverified version of an image to a verified version takes less than a second :smile:

**Comment by czhang03** [comment] 2024-03-01 17:09
Here is the output:
```
systemctl status cups
● cups.service - CUPS Scheduler
     Loaded: loaded (/usr/lib/systemd/system/cups.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Fri 2024-03-01 12:02:33 EST; 5min ago
TriggeredBy: ● cups.path
             ● cups.socket
       Docs: man:cupsd(8)
   Main PID: 4023 (cupsd)
     Status: "Scheduler is running..."
      Tasks: 1 (limit: 38254)
     Memory: 8.3M
        CPU: 49ms
     CGroup: /system.slice/cups.service
             └─4023 /usr/sbin/cupsd -l

Mar 01 12:03:51 fedora cupsd[4023]: Saving subscriptions.conf...
Mar 01 12:03:51 fedora cupsd[4023]: cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
Mar 01 12:03:51 fedora cupsd[4023]: Expiring subscriptions...
Mar 01 12:03:51 fedora cupsd[4023]: Report: clients=1
Mar 01 12:03:51 fedora cupsd[4023]: Report: jobs=2
Mar 01 12:03:51 fedora cupsd[4023]: Report: jobs-active=0
Mar 01 12:03:51 fedora cupsd[4023]: Report: printers=1
Mar 01 12:03:51 fedora cupsd[4023]: Report: stringpool-string-count=758
Mar 01 12:03:51 fedora cupsd[4023]: Report: stringpool-alloc-bytes=9904
Mar 01 12:03:51 fedora cupsd[4023]: Report: stringpool-total-bytes=14056
```

**Comment by czhang03** [comment] 2024-03-01 17:17
I think this might be the problem, SANE uses different port than cups, I think we might need to enable additional port for scanning to work: https://en.opensuse.org/SDB:CUPS_and_SANE_Firewall_settings

But this still doesn't explain why gnome cannot auto discover the drivers. It seems like CUPS can discover the driver just fine, since `lpadmin -p Printer -E -v ipp://<IP Address>/ipp/print -m everywhere` works.

**Comment by RoyalOughtness** [comment] 2024-03-01 17:31
Please let me know what config changes you apply to make the issue go away.

**Comment by czhang03** [comment] 2024-03-01 17:34
I was not able to make this issue go away yet, I am digging in to SANE documentation is various firewall setting to see if they work, but at this point, has not encountered a setting that works.

**Comment by RoyalOughtness** [comment] 2024-03-01 17:39
Have you confirmed that the issue is definitely firewall related?

This can be accomplished by temporarily disabling the firewall and checking for a repro.

**Comment by czhang03** [comment] 2024-03-01 17:47
Yeap, once firewalld is disabled it scans fine.

**Comment by RoyalOughtness** [comment] 2024-03-01 17:48
@czhang03 cool, once you figure out once port is needed please add it to the just command for enabling cups and then this issue can be closed

**Comment by czhang03** [comment] 2024-03-01 18:24
Okay, I give up. I tried all the port mentioned anywhere, and never got anything. Here is some documentation I found:

https://en.opensuse.org/SDB:CUPS_and_SANE_Firewall_settings
https://wiki.archlinux.org/title/SANE#Firewall
http://www.sane-project.org/man/sane-pixma.5.html
https://wiki.debian.org/SaneOverNetwork

Suggestions typically include adding `6566/tcp`,  `8610/udp` (for MFNP), `8612/udp` (for BJNP), plus all the ports mentioned in `data_portrange` in `/etc/sane.d/saned.conf`, which is suggested to be `30000 - 30100`. 

I will try to do some more testing, if I find nothing in the next half hour, then I guess I cannot spend more time on this.

**Comment by czhang03** [comment] 2024-03-01 18:58
I run a `tcpdump` during scanner discovery and scanning, and discover that the ports are all over the place definitely includes the ones that listed above, but also includes many others. I don't know any way to make this reliable. 

Even `firewall-cmd --zone=trusted --add-source=<printer ip>` do not work (discover is fine, but the scanning and printing don't work)...

For now, I will just turn off firewall when I print, and turn it back on when I am done...

**Comment by RoyalOughtness** [comment] 2024-03-01 19:08
Okay, I'll close this for now but if you figure out which port is needed please open a PR

**Closed as not planned by RoyalOughtness** 2024-03-01 19:08 UTC

**Comment by czhang03** [comment] 2024-03-03 16:40
I don't know if we should leave this open, so that people more skilled than me can take a look.

**Comment by RoyalOughtness** [comment] 2024-03-03 18:23
did you already try this?

`firewall-cmd --permanent --zone=private --add-service=sane`

**Comment by czhang03** [comment] 2024-03-03 22:50
Yes, I believe it only opens up port 6566, which is not enough according to the resources I listed above.

https://github.com/firewalld/firewalld/blob/main/config/services/sane.xml

**Comment by RoyalOughtness** [comment] 2024-03-04 02:05
@czhang03 So neither method worked? And yet disabling the firewall worked?

**Comment by czhang03** [comment] 2024-03-04 13:28
@qoijjj yes.once the firewall is disabled by `systemctl stop firewalld` then everything (printer discovery, printer driver discovery, printing and scanning) works.

Only following the above firewall setup guides, including but not limited to `just eable-cups` and `firewall-cmd --permanent --zone=private --add-service=sane`, I will need to manually add the printer from IP and manually select printer driver, and scanning still doesn't work.

**Comment by RoyalOughtness** [comment] 2024-03-04 16:52
Very strange. What if you leave the firewall on and allow all ports temporarily?
