### ISSUE TITLE
Change yafti Flatpak installs

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#35] opened 2023-11-25 22:48 UTC
Yafti is ublues tool using a dialog to automatically install specific flatpak apps on first login. It uses GTK, thats why GTK is a dependency even on KDE. It doesn't seem to be active yet.

**Comment by RoyalOughtness** [comment] 2023-11-25 23:34
Right, it serves no use without flatpak, so it can be enabled after flatpaks are working

**Comment by boredsquirrel** [comment] 2023-11-26 00:22
another thing is the KDE welcome dialog.

1. Just "debloating" it is pretty shitty towards the KDE community
2. it allows custom pages, and when I have time I want to do one in QML targeted towards Kinoite. The origin was the spontaneous removal of Okular and Gwenview, which could be made smoother with this dialog. We could use it to explain the distro, and also allow to install some apps.

**Comment by RoyalOughtness** [comment] 2023-11-26 00:24
> another thing is the KDE welcome dialog.
> 
> 1. Just "debloating" it is pretty shitty towards the KDE community

Do not reuse irrelevant issues for other issues. If you want to add back the kde welcome dialog, submit a PR.

**Comment by RoyalOughtness** [comment] 2023-11-29 23:44
duplicate of https://github.com/secureblue/secureblue/issues/65

**Closed as not planned by RoyalOughtness** 2023-11-29 23:44 UTC
