### ISSUE TITLE
Questions about the project scope and goals.

### ISSUE THREAD

**Issue by Malom-ctrl** [secureblue/secureblue#155] opened 2024-01-08 01:44 UTC
Hi there,

I've stumbled upon this repo a few days ago and i find it very interesting. I have read through a fair number of the PR/issues to get a better understanding of the project.
This is a very appealing project to me, so i would gladly get involved.

Although I have a few questions :

 - Does Secureblue aim to close the gap in security between regular fedora and things like GrapheneOS or ChromeOS as much as possible ? (I understand there are hardware limitations as well as some software limitations such as true verified boot which are most likely completely out of scope). But is the goal to get as close to those as possible ? Or are you going for something else ?
 
  - Are ideas/PRs that are purely based on user-friendliness (without compromising the security of course) out of scope ? In which case i guess that would mean Secureblue would be the core on top of which other people could create some more or less userfriendly forks. But it may be less cohesive. What are your thoughts on that ?
  
  I'm really looking forward to what this project will become.

**Comment by RoyalOughtness** [comment] 2024-01-08 01:59
Thanks and welcome!

>  to close the gap in security between regular fedora and things like GrapheneOS or ChromeOS as much as possible ?

As much as possible while also avoiding sacrificing usability as much as possible. For example, unplugging your computer would be the most secure option, but it's not very usable :smile: 

GrapheneOS is a good example of striking this balance. Unfortunately though there is no desktop linux distro that compares to android or ios in terms of security. Desktop linux is just generally lacking in security. It's all relative and so our goal at secureblue isn't to claim we accomplished a secure linux desktop, but to take full advantage of the advances that do exist for desktop linux and maintain a secure image relative to other linux desktops.

> purely based on user-friendliness out of scope 

As a general rule, yes. Unless it specifically pertains to fixing bugs caused by secureblue changes. Some examples would be the changes in this directory: https://github.com/secureblue/secureblue/tree/live/config/files/usr/etc/systemd

There we made some specific changes to services that were impacted negatively by the global changes.

Other than that, UX changes are going to be upstream and/or out of scope. Secureblue has a specific scope and we should stay focused on that scope. If for example you think that systemd's UX is lacking or that ublue should include new UX functionality, those suggestions belong in tickets against systemd or ublue.

**Comment by Malom-ctrl** [comment] 2024-01-08 02:15
Thanks for your answers !

I agree GrapheneOS is a great example. We can't, at least at the moment, do anything to reach that level of security on desktop platforms. That's why i also mentioned ChromeOS because it's basically a linux distro with a ton of hardening, which means there is much more we can do to close the gap there. I guess that could be a great inspiration and source of ideas for Secureblue.

Regarding the way ChromeOS works, i have some ideas that "could" be in scope for secureblue. But i think it's a lot of work and maybe not even doable. I will open another issue to discuss that.

**Comment by RoyalOughtness** [comment] 2024-01-08 02:22
> Regarding the way ChromeOS works, i have some ideas that "could" be in scope for secureblue. But i think it's a lot of work and maybe not even doable. I will open another issue to discuss that.

Please do! There's only so much that we can do without restricting what hardware secureblue can be used on (like GrapheneOS does). That said though if there are any gaps we can fill relative to ChromeOS or GrapheneOS it's certainly worth discussing.

I'll close out this issue and we can discuss your ideas in their respective issues. Thanks again for your questions and suggestions.

**Closed as completed by RoyalOughtness** 2024-01-08 02:22 UTC

**Comment by boredsquirrel** [comment] 2024-01-20 18:23
hey, if secureblue is used as the base, which branch would be used?

there are always `template` (ublue base) and `live`.

Would a fork then use the `live` branch as base, and create a `live-modded` branch?

**Comment by RoyalOughtness** [comment] 2024-01-20 18:35
@trytomakeyouprivate you would want to use live for a fork

However, even easier than forking would be to use [startingpoint](https://github.com/ublue-os/startingpoint) the same way this project does and the use secureblue as your base image. Then you're just ingesting an identical secureblue image and making changes on top of it. This would be more maintainable than constantly having to keep in sync with secureblue :smile:

**Comment by boredsquirrel** [comment] 2024-01-20 22:19
Nice, thanks!
