### ISSUE TITLE
Add rust + cargo by default?

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#78] opened 2023-11-29 23:32 UTC
layering `rust cargo` should deal with that, at least in rpm-ostree.

cargo allows users to compile software, which may be preferred or even needed for some projects. 

This is not included upstream and will not be added, apart from Bluefin probably.

**Comment by RoyalOughtness** [comment] 2023-11-29 23:35
This is a duplicate of the issue to get distrobox / toolbox working. Adding devtools to the base image is out of scope.

**Closed as not planned by RoyalOughtness** 2023-11-29 23:35 UTC

**Comment by boredsquirrel** [comment] 2023-11-30 02:53
distrobox/toolbox is mainly to install apps not available on Fedora, or to isolate dependencies.

Leaving out devtools of course, but for installing apps? Agree on rust+cargo, might be a little nieche, but distrobox was excluded because it currently does not work, wasn't it?

**Comment by RoyalOughtness** [comment] 2023-11-30 02:55
> distrobox/toolbox is mainly to install apps not available on Fedora, or to isolate dependencies.

That is not correct. They are intended as dev environments. https://universal-blue.org/introduction/?h=development+environment#mindset
