### ISSUE TITLE
Disable services through empty desktop files

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#108] opened 2023-12-06 00:59 UTC
I only know the services on KDE

```
>> ls /etc/xdg/autostart/
org.kde.kdeconnect.daemon.desktop
org.kde.plasma-welcome.desktop
geoclue-demo-agent.desktop
org.kde.discover.notifier.desktop
vboxclient.desktop
spice-vdagent.desktop
vmware-user.desktop
```
Removing these files will stop the services from autostarting. Users can still add them in their user `~/.config/autostart` if they wish to (just script?)

This could be a solution to remove unwanted stuff, and also kde-connect, without uninstalling it.

CUPS is controlled through systemd, which is also easy to disable

**Comment by RoyalOughtness** [comment] 2023-12-06 02:46
Duplicate of https://github.com/secureblue/secureblue/issues/57 and https://github.com/secureblue/secureblue/issues/33

Please do not open new issues to discuss existing issues.

**Closed as not planned by RoyalOughtness** 2023-12-06 02:46 UTC
