### ISSUE TITLE
[BUG] Local Dconf Permission denied

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#417] opened 2024-09-05 11:36 UTC
**Describe the bug**
My custom image based on silverblue-main-hardened includes `/etc/dconf/db/local` file with custom gschema. There are no errors on building or running `dconf update`. However none of these cusom gschemas in local file are applied.
One day I rerun yafti for something else and the error came up:

`dconf-WARNING .... unable to open file /etc/dconf/db/local .... Permission denied; expect degraded performance`

Perhaps that's why local file gschema are not set.

System should be able to read these local dconf files to compile them together.

**Comment by ghost** [comment] 2024-09-05 14:49
I have the same issue on the silveblue image `main-userns-hardened` since fixing authselect.

**Comment by RoyalOughtness** [comment] 2024-09-05 16:11
please provide `ls -l /etc/dconf/db/local`

**Comment by ghost** [comment] 2024-09-05 16:18
`-rw-r-----. 1 root root 104 Aug 22 --:13 /etc/dconf/db/local`

**Comment by RoyalOughtness** [comment] 2024-09-05 16:19
> `-rw-r-----. 1 root root 104 Aug 22 --:13 /etc/dconf/db/local`

run `chmod 644 /etc/dconf/db/local`, should fix it.

**Comment by ghost** [comment] 2024-09-05 16:22
the other one is fixed, but `(process:14194): dconf-WARNING **: --:21:28.985: unable to open file '/etc/dconf/db/site': Failed to open file “/etc/dconf/db/site”: open() failed: Permission denied; expect degraded performance` still remains.

**Comment by RoyalOughtness** [comment] 2024-09-05 16:24
same thing

**Comment by fiftydinar** [comment] 2024-09-05 16:26
Maybe Rechunk causes those permission issues?

**Comment by RoyalOughtness** [comment] 2024-09-05 16:26
@fiftydinar we don't rechunk unless you mean upstream?

**Comment by fiftydinar** [comment] 2024-09-05 16:27
> @fiftydinar we don't rechunk unless you mean upstream?

Upstream

**Comment by ghost** [comment] 2024-09-05 16:28
@qoijjj, did it for all folders, fixed now, thanks. :+1:

**Comment by RoyalOughtness** [comment] 2024-09-05 16:40
@fiftydinar im seeing 644 in the same image in /usr/etc, so this is likely an issue caused by incorrect permissions when modifying /etc

**Closed as not planned by RoyalOughtness** 2024-09-05 16:40 UTC
